#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(shinythemes)

# Define UI for application that draws a histogram
shinyUI(
  fluidPage(
    theme=shinytheme("yeti"), #otros tipos de temas "yeti", "cerulean", "superhero", 

    
    # Application title
    titlePanel(h2("Calculadora de salario", align = "center")),
    h4("Calculá cuánto vale el trabajo no remunerado", align = "center"),
    
    tabsetPanel(
        tabPanel("ENUT",
                 sidebarLayout(position = "right",
                               sidebarPanel(
                                 submitButton("Enviar", icon("refresh")),
                                 helpText("Para enviar tus datos da click al boton"),
                                 
                                 p("El ingreso según la ENUT"),
                                 textOutput("ingreso")
                                            
                               ),
                               mainPanel(
                                 tabsetPanel(
                                   tabPanel("Caracteristicas personales",
                                            h4("Ingresa tus caracteristicas:"),
                                            flowLayout(selectInput("Estado",
                                                                   "Estado de residencia",
                                                                   c("Aguascalientes","Baja California", 
                                                                     "Baja California Sur", "Campeche", 
                                                                     "Coahuila", "Colima", "Chiapas", 
                                                                     "Chihuahua", "Durango", "Distrito Federal", 
                                                                     "Guanajuato", "Guerrero", "Hidalgo", 
                                                                     "Jalisco", "México", "Michoacán", "Morelos", 
                                                                     "Nayarit", "Nuevo León", "Oaxaca", "Puebla", 
                                                                     "Querétaro", "Quintana Roo", "San Luis Potosí", 
                                                                     "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", 
                                                                     "Tlaxcala", "Veracruz", "Yucatán","Zacatecas")),
                                                       radioButtons("Sexo",
                                                                    "Sexo",
                                                                    c("Hombre","Mujer")),
                                                       sliderInput("Escolaridad",
                                                                   "Años de escolaridad",
                                                                   0,
                                                                   30,
                                                                   9),
                                                       numericInput(inputId="Edad",
                                                                    label="Edad",
                                                                    20,
                                                                    12,
                                                                    98),
                                                       selectInput("EstadoCivil",
                                                                   "Estado Civil",
                                                                   c("Pareja en unión libre",
                                                                     "Separado",
                                                                     "Divorciado",
                                                                     "Viudo",
                                                                     "Casado",
                                                                     "Soltero")),
                                                       radioButtons("Urbano",
                                                                    "¿Vives en un entorno rural o urbano?",
                                                                    c("Rural","Urbano")),
                                                       radioButtons("Indigena",
                                                                    "¿Se considera indígena?",
                                                                    c("Sí","No"))
                                                       )
                                            ),
                                   
                                   tabPanel("Acceso a seguridad social",
                                            h4("Ingresa tus datos de afiliación:"),
                                            flowLayout(radioButtons("Afiliacion",
                                                                    "¿Está afiliado a algún servicio médico?",
                                                                    c("Sí","No")),
                                                       radioButtons("ProgramaSocial",
                                                                    "¿Recientemente tramitó o cobró un programa social?",
                                                                    c("Sí","No")))),
                                   tabPanel("Caracteristicas del hogar",
                                            h4("Ingresa las caracteristicas de tu hogar:"),
                                            flowLayout(numericInput("nPersonas",
                                                                    "¿Cuántos integrantes conforman tu hogar? (Incluyéndote a ti)",
                                                                    1,
                                                                    20),
                                                       selectInput("Paren",
                                                                   "¿Qué es usted del jefe de hogar?",
                                                                   c("Soy jefe de hogar",
                                                                     "Cónyuge/Pareja",
                                                                     "Hijo/Hija",
                                                                     "Nieto",
                                                                     "Yerno/Nuera",
                                                                     "Padre/Madre/Suegro",
                                                                     "Otro pariente",
                                                                     "Sin parentezco")),
                                                       radioButtons("SexoJefe",
                                                                    "El/la jefe de tu hogar es:",
                                                                    c("Hombre", "Mujer")),
                                                       numericInput("EdadJefe",
                                                                    "Edad del jefe del hogar",
                                                                    12,
                                                                    98),
                                                       sliderInput("EscJefe",
                                                                   "Escolaridad del jefe de hogar",
                                                                   0,
                                                                   30,
                                                                   9)
                                            ))
                          )))),#tabpanel
      tabPanel("ENOE",
               sidebarLayout(position = "right",
                            sidebarPanel(
                              submitButton("Enviar", icon("refresh")),
                              helpText("Para enviar tus datos da click al boton"),
                              
                              p("El ingreso según la ENOE"),
                              textOutput("ingreso")
                              
                            ),
                            mainPanel(
                              tabsetPanel(
                                tabPanel("Caracteristicas personales",
                                         h4("Ingresa tus caracteristicas:"),
                                         flowLayout(selectInput("Entidad",
                                                                "Entidad Federativa",
                                                                choices = c("Aguascalientes",
                                                                            "Baja California", 
                                                                            "Baja California Sur", 
                                                                            "Campeche", 
                                                                            "Coahuila", 
                                                                            "Colima", 
                                                                            "Chiapas", 
                                                                            "Chihuahua", 
                                                                            "Ciudad de México",
                                                                            "Durango",
                                                                            "Estado de México",
                                                                            "Guanajuato", 
                                                                            "Guerrero", 
                                                                            "Hidalgo", 
                                                                            "Jalisco", 
                                                                            "Michoacán", 
                                                                            "Morelos", 
                                                                            "Nayarit", 
                                                                            "Nuevo León", 
                                                                            "Oaxaca", 
                                                                            "Puebla", 
                                                                            "Querétaro", 
                                                                            "Quintana Roo", 
                                                                            "San Luis Potosí", 
                                                                            "Sinaloa", 
                                                                            "Sonora", 
                                                                            "Tabasco", 
                                                                            "Tamaulipas", 
                                                                            "Tlaxcala", 
                                                                            "Veracruz", 
                                                                            "Yucatán", 
                                                                            "Zacatecas")),
                                                                selectInput("Sexo",
                                                                            "Sexo",
                                                                            choices = c("Hombre",
                                                                                        "Mujer")),
                                                                numericInput("Edad",
                                                                             "Edad",
                                                                             20,
                                                                             12,
                                                                             98),
                                                                sliderInput("Anios_esc",
                                                                            "Años de escolaridad",
                                                                            0,
                                                                            30,
                                                                            9),
                                                                selectInput("e_con",
                                                                            "Estado Conyugal",
                                                                            choices = c("Unión libre",
                                                                                        "Separado(a)",
                                                                                        "Divorciado(a)",
                                                                                        "Viudo(a)",
                                                                                        "Casado(a)",
                                                                                        "Soltero(a)",
                                                                                        "No sabe")),
                                                                radioButtons("Zona",
                                                                             "¿Vives en un entorno rural o urbano?",
                                                                             choices=c("Urbano",
                                                                                       "Rural")),
                                                                selectInput("hij5s",
                                                                            "¿Cuántos hijos tienes? (si eres hombre responde: no aplica)",
                                                                            c("No aplica",
                                                                            "Sin hijos",
                                                                            "De 1 a 2 hijos",
                                                                            "De 3 a 5 hijos",
                                                                            "De 6 hijos y más")))),
                                
                                         tabPanel("Sector laboral",
                                                  h4("Ingresa tus datos de trabajo:"),
                                                  flowLayout(numericInput("Exp",
                                                                          "Años de experiencia laboral",
                                                                          value=10),
                                                             selectInput("mil_f2",
                                                                         "Sector Laboral",
                                                                         choices = c("Sector Informal",
                                                                                     "Trabajo doméstico remunerado",
                                                                                     "Empresas,gobiernos e instituciones",
                                                                                     "Sector agropecuario",
                                                                                     "No aplica")),
                                                             radioButtons("Seguridad Social",
                                                                          "¿Cuentas con acceso a Seguridad Social?",
                                                                          choices=c("Sí",
                                                                                    "No")))),
                                         tabPanel("Tiempo de cuidado",
                                                  h4("Ingresa el tiempo de cada actividad:"),
                                                  flowLayout(numericInput("p3.1",
                                                                          "¿Cuánto tiempo pasó en la semana en recoger o esperar a algún adulto mayor para que recibiera atención de salud?",
                                                                          value=10),
                                                             numericInput("p3.2",
                                                                          "¿Cuánto tiempo pasó en la semana en apoyar o asesorar a algún adulto mayor en el uso de la computadora, celular, internet o actividades relacionadas con sus cursos o clases?",
                                                                          value=10),
                                                             numericInput("p3.3",
                                                                          "¿usted llevó y/o recogió a algún adulto mayor del trabajo, de algún trámite u otro lugar?",
                                                                          value=10),    
                                                             numericInput("p3.4",
                                                                          "¿Cuánto tiempo pasó en la semana, mientras hacía otra cosa, cuidó o estuvo al pendiente de algún adulto mayor?",
                                                                          value=10),
                                                             numericInput("p3.5",
                                                                          "Sea en la casa, hospital u otro lugar, ¿Cuánto tiempo pasó en la semana en darles de comer o ayudó a hacerlo?",
                                                                          value=10), 
                                                             numericInput("p3.6",
                                                                          "¿Cuánto tiempo pasó en la semana bañando, aseando, vistiendo, arreglando o ayudando a hacerlo a algún adulto mayor?",
                                                                          value=10), 
                                                             
                                                             numericInput("p3.7",
                                                                          "¿Cuánto tiempo pasó en la semana usted cargó, acostó o le ayudó a un adulto mayor a hacerlo?",
                                                                          value=10),
                                                             numericInput("p3.8",
                                                                          "¿Cuánto tiempo pasó preparando remedios caseros o algún alimento especial?",
                                                                          value=10),
                                                             numericInput("p3.9",
                                                                          "¿Cuánto tiempo pasó dando medicamentos o checando los síntomas de algún adulto mayor? ",
                                                                          value=10),
                                                             numericInput("p3.10",
                                                                          "¿Cuánto tiempo pasó recogiendo o esperando a algún adulto mayor para que recibiera atención de salud?",
                                                                          value=10),
                                                             numericInput("p3.11",
                                                                          "¿Cuánto tiempo pasó dando terapia especial o ayudando a realizar ejercicios a algún adulto mayor?",
                                                                          value=10),
                                                             numericInput("p3.12",
                                                                          "¿Cuánto tiempo pasó llevando y/o recogiendo de clases, trabajo u otro lugar a algún adulto mayor?",
                                                                          value=10),
                                                             numericInput("p3.13",
                                                                          "¿Cuánto tiempo pasó ayudando o apoyando en las tareas de la escuela o trabajo a algún adulto mayor?",
                                                                          value=10)))),
                                                             
                                                                ))),
      tabPanel("AMAI",
               sidebarLayout(
                 sidebarPanel(
                   h3("Hogar"),
                   flowLayout(selectInput("Esc_jefe",
                                          "¿Cuál fue el último año de estudios del jefe de hogar?",
                                          c("No estudió",
                                            "Primaria incompleta",
                                            "Primaria completa",
                                            "Secundaria incompleta",
                                            "Secundaria completa",
                                            "Preparatoria incompleta",
                                            "Preparatoria completa",
                                            "Licenciatura incompleta",
                                            "Licenciatura completa",
                                            "Diplomado o maestría")),
                              numericInput(inputId="Numeroautos",
                                           label=" ¿Cuántos automóviles o camionetas tienen?",
                                           0,
                                           0,
                                           20),
                              radioButtons("Internet",
                                           "¿Su hogar cuenta con internet?",
                                           c("Si tengo","No tengo")),
                              sliderInput("Numerotrabajadores",
                                          "¿Cuántas personas mayores a 14 años trabajaron en el último mes?",
                                          0,
                                          20,
                                          5)),
                   h3("Vivienda"),
                   flowLayout(numericInput(inputId="Numerobaños",
                                           label="¿Cuántos baños completos hay en la vivienda?",
                                           0,
                                           0,
                                           20),
                              sliderInput("Numerocuartos",
                                          "¿cuántos cuartos se usan para dormir?",
                                          0,
                                          20,
                                          8))
               ),
               mainPanel(
                 h3("NSE"),
                 p("El", em("Índice de Niveles Socioeconómicos (NSE)"), ", 
                   creado por la", strong("Asociación Mexicana de agencias de 
                   Inteligencia de Mercado y Opinión (AMAI), "), "es la regla, 
                   basada en un modelo estadístico, que permite agrupar y 
                   clasificar a los hogares mexicanos en siete niveles, de 
                   acuerdo a su capacidad para satisfacer las necesidades de sus
                   integrantes."),
                 textOutput("txtOutput"),
                 hr(),
                 img(src="imagen.png", 
                     align = "center", 
                     height = 420, 
                     width = 320),
                 img(src="imagen 2.png", 
                     align = "center", 
                     height = 420, 
                     width = 320))))
      
    )#tabsetPanel,
  )#fluidPage
)#ShinyUI