#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(shinythemes)

# Define UI for application that draws a histogram
shinyUI(
  fluidPage(
    theme=shinytheme("yeti"), #otros tipos de temas "yeti", "cerulean", "superhero", 

    
    # Application title
    titlePanel(h2("Calculadora de salario", align = "center")),
    h4("Calculá cuánto vale el trabajo no remunerado", align = "center"),
    
    tabsetPanel(
        tabPanel("ENUT", style = "color:purple",
                 sidebarLayout(position = "right",
                               sidebarPanel(
                                 #actionButton("do", "Click Me"),
                                 submitButton("Enviar", icon("refresh")),
                                 helpText("Para enviar tus datos da click al boton"),
                                 
                                 p("El ingreso según la ENUT"),
                                 #textOutput("ingreso")
                                            
                               ),
                               mainPanel(
                                 tabsetPanel(
                                   tabPanel("Caracteristicas personales",
                                            h4("Ingresa tus caracteristicas:", align = "center"),
                                            flowLayout(selectInput("Estado",
                                                                   "Estado de residencia",
                                                                   c("Aguascalientes","Baja California", 
                                                                     "Baja California Sur", "Campeche", 
                                                                     "Coahuila", "Colima", "Chiapas", 
                                                                     "Chihuahua", "Durango", "Distrito Federal", 
                                                                     "Guanajuato", "Guerrero", "Hidalgo", 
                                                                     "Jalisco", "México", "Michoacán", "Morelos", 
                                                                     "Nayarit", "Nuevo León", "Oaxaca", "Puebla", 
                                                                     "Querétaro", "Quintana Roo", "San Luis Potosí", 
                                                                     "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", 
                                                                     "Tlaxcala", "Veracruz", "Yucatán","Zacatecas")),
                                                       radioButtons("Sexo",
                                                                    "Sexo",
                                                                    c("Hombre","Mujer")),
                                                       sliderInput("Escolaridad",
                                                                   "Años de escolaridad",
                                                                   0,
                                                                   30,
                                                                   9),
                                                       numericInput(inputId="Edad",
                                                                    label="Edad",
                                                                    20,
                                                                    12,
                                                                    98),
                                                       selectInput("EstadoCivil",
                                                                   "Estado Civil",
                                                                   c("Pareja en unión libre",
                                                                     "Separado",
                                                                     "Divorciado",
                                                                     "Viudo",
                                                                     "Casado",
                                                                     "Soltero")),
                                                       radioButtons("Urbano",
                                                                    "¿Vives en un entorno rural o urbano?",
                                                                    c("Rural","Urbano")),
                                                       radioButtons("Indigena",
                                                                    "¿Se considera indígena?",
                                                                    c("Sí","No")),
                                                       radioButtons("Afiliacion",
                                                                    "¿Está afiliado a algún servicio médico?",
                                                                    c("Sí","No")),
                                                       radioButtons("ProgramaSocial",
                                                                    "¿Recientemente tramitó o cobró un programa social?",
                                                                    c("Sí","No")))),

                                   #tabPanel("Acceso a seguridad social",
                                            #h4("Ingresa tus datos de afiliación:", align = "center"),
                                            #flowLayout(radioButtons("Afiliacion",
                                                                    #"¿Está afiliado a algún servicio médico?",
                                                                    #c("Sí","No")),
                                                       #radioButtons("ProgramaSocial",
                                                                    #"¿Recientemente tramitó o cobró un programa social?",
                                                                    #c("Sí","No")))),
                                   tabPanel("Caracteristicas del hogar",
                                            h4("Ingresa las caracteristicas de tu hogar:", align = "center"),
                                            flowLayout(numericInput("nPersonas",
                                                                    "¿Cuántos integrantes conforman tu hogar? (Incluyéndote a ti)",
                                                                    1,
                                                                    20),
                                                       selectInput("Paren",
                                                                   "¿Qué es usted del jefe de hogar?",
                                                                   c("Soy jefe de hogar",
                                                                     "Cónyuge/Pareja",
                                                                     "Hijo/Hija",
                                                                     "Nieto",
                                                                     "Yerno/Nuera",
                                                                     "Padre/Madre/Suegro",
                                                                     "Otro pariente",
                                                                     "Sin parentezco")),
                                                       radioButtons("SexoJefe",
                                                                    "El/la jefe de tu hogar es:",
                                                                    c("Hombre", "Mujer")),
                                                       numericInput("EdadJefe",
                                                                    "Edad del jefe del hogar",
                                                                    12,
                                                                    98),
                                                       sliderInput("EscJefe",
                                                                   "Escolaridad del jefe de hogar",
                                                                   0,
                                                                   30,
                                                                   9)
                                            )),
                                   tabPanel("Tiempo de cuidado",
                                            h4("¿Cuánto tiempo dedicas, en un semana habitual, a las siguientes tareas?:", align = "center"),
                                            h6("Ingresa la cantidad de horas a la semana que te lleva realizar cada una, ya sea en la casa, hospital u otro lugar", align = "center"),
                                            br(),
                                            flowLayout(numericInput("p5.1",
                                                                    "Recoger o esperar a algún adulto mayor para que recibiera atención de salud",
                                                                    value=10),
                                                       numericInput("p5.2",
                                                                    "Apoyar o asesorar a algún adulto mayor en el uso de la computadora, celular, internet o actividades relacionadas a cursos o clases",
                                                                    value=10),
                                                       numericInput("p5.3",
                                                                    "Llevar y/o recoger a algún adulto mayor del trabajo, de algún trámite u otro lugar",
                                                                    value=10),    
                                                       numericInput("p5.4",
                                                                    "Cuidar o estar al pendiente de algún adulto mayor, mientras hacía otra cosa",
                                                                    value=10),
                                                       numericInput("p5.5",
                                                                    "Dar de comer o ayudar a algún adulto mayor a hacerlo",
                                                                    value=10), 
                                                       numericInput("p5.6",
                                                                    "Asear, vestir, arreglar o ayudar a algún adulto mayor a hacerlo",
                                                                    value=10), 
                                                       numericInput("p5.7",
                                                                    "Cargar, acostar o ayudar a algún adulto mayor a hacerlo",
                                                                    value=10),
                                                       numericInput("p5.8",
                                                                    "Preparar remedios caseros o algún alimento especial a algún adulto mayor",
                                                                    value=10),
                                                       numericInput("p5.9",
                                                                    "Dar medicamentos o checar los síntomas de algún adulto mayor",
                                                                    value=10),
                                                       numericInput("p5.11",
                                                                    "Dar terapia especial o ayudar a realizar ejercicios a algún adulto mayor",
                                                                    value=10),
                                                       numericInput("p5.13",
                                                                    "Ayudar o apoyar en el trabajo de algún adulto mayor",
                                                                    value=10))))
                          ))),#tabpanel
      tabPanel("ENOE",
               sidebarLayout(position = "right",
                            sidebarPanel(
                              submitButton("Enviar", icon("refresh")),
                              helpText("Para enviar tus datos da click al boton"),
                              
                              p("El ingreso según la ENOE"),
                              #textOutput("ingreso")
                              
                            ),
                            mainPanel(
                              tabsetPanel(
                                tabPanel("Caracteristicas personales",
                                         h4("Ingresa tus caracteristicas:", align = "center"),
                                         flowLayout(selectInput("Entidad",
                                                                "Entidad Federativa",
                                                                choices = c("Aguascalientes",
                                                                            "Baja California", 
                                                                            "Baja California Sur", 
                                                                            "Campeche", 
                                                                            "Coahuila", 
                                                                            "Colima", 
                                                                            "Chiapas", 
                                                                            "Chihuahua", 
                                                                            "Ciudad de México",
                                                                            "Durango",
                                                                            "Estado de México",
                                                                            "Guanajuato", 
                                                                            "Guerrero", 
                                                                            "Hidalgo", 
                                                                            "Jalisco", 
                                                                            "Michoacán", 
                                                                            "Morelos", 
                                                                            "Nayarit", 
                                                                            "Nuevo León", 
                                                                            "Oaxaca", 
                                                                            "Puebla", 
                                                                            "Querétaro", 
                                                                            "Quintana Roo", 
                                                                            "San Luis Potosí", 
                                                                            "Sinaloa", 
                                                                            "Sonora", 
                                                                            "Tabasco", 
                                                                            "Tamaulipas", 
                                                                            "Tlaxcala", 
                                                                            "Veracruz", 
                                                                            "Yucatán", 
                                                                            "Zacatecas")),
                                                                selectInput("Sexo",
                                                                            "Sexo",
                                                                            choices = c("Hombre",
                                                                                        "Mujer")),
                                                                numericInput("Edad",
                                                                             "Edad",
                                                                             20,
                                                                             12,
                                                                             98),
                                                                sliderInput("Anios_esc",
                                                                            "Años de escolaridad",
                                                                            0,
                                                                            30,
                                                                            9),
                                                                selectInput("e_con",
                                                                            "Estado Conyugal",
                                                                            choices = c("Unión libre",
                                                                                        "Separado(a)",
                                                                                        "Divorciado(a)",
                                                                                        "Viudo(a)",
                                                                                        "Casado(a)",
                                                                                        "Soltero(a)",
                                                                                        "No sabe")),
                                                                radioButtons("Zona",
                                                                             "¿Vives en un entorno rural o urbano?",
                                                                             choices=c("Urbano",
                                                                                       "Rural")),
                                                                selectInput("hij5s",
                                                                            "¿Cuántos hijos tienes? (si eres hombre responde: no aplica)",
                                                                            c("No aplica",
                                                                            "Sin hijos",
                                                                            "De 1 a 2 hijos",
                                                                            "De 3 a 5 hijos",
                                                                            "De 6 hijos y más")))),
                                
                                         tabPanel("Sector laboral",
                                                  h4("Ingresa tus datos de trabajo:", align = "center"),
                                                  flowLayout(numericInput("Exp",
                                                                          "Años de experiencia laboral",
                                                                          value=10),
                                                             selectInput("mil_f2",
                                                                         "Sector Laboral",
                                                                         choices = c("Sector Informal",
                                                                                     "Trabajo doméstico remunerado",
                                                                                     "Empresas,gobiernos e instituciones",
                                                                                     "Sector agropecuario",
                                                                                     "No aplica")),
                                                             radioButtons("Seguridad Social",
                                                                          "¿Cuentas con acceso a Seguridad Social?",
                                                                          choices=c("Sí",
                                                                                    "No")))),
                                         tabPanel("Tiempo de cuidado",
                                                  h4("¿Cuánto tiempo dedicas, en un semana habitual, a las siguientes tareas?:", align = "center"),
                                                  h6("Ingresa la cantidad de horas a la semana que te lleva realizar cada una, ya sea en la casa, hospital u otro lugar", align = "center"),
                                                  br(),
                                                  flowLayout(numericInput("p3.1",
                                                                          "Recoger o esperar a algún adulto mayor para que recibiera atención de salud",
                                                                          value=10),
                                                             numericInput("p3.2",
                                                                          "Apoyar o asesorar a algún adulto mayor en el uso de la computadora, celular, internet o actividades relacionadas a cursos o clases",
                                                                          value=10),
                                                             numericInput("p3.3",
                                                                          "Llevar y/o recoger a algún adulto mayor del trabajo, de algún trámite u otro lugar",
                                                                          value=10),    
                                                             numericInput("p3.4",
                                                                          "Cuidar o estar al pendiente de algún adulto mayor, mientras hacía otra cosa",
                                                                          value=10),
                                                             numericInput("p3.5",
                                                                          "Dar de comer o ayudar a algún adulto mayor a hacerlo",
                                                                          value=10), 
                                                             numericInput("p3.6",
                                                                          "Asear, vestir, arreglar o ayudar a algún adulto mayor a hacerlo",
                                                                          value=10), 
                                                             numericInput("p3.7",
                                                                          "Cargar, acostar o ayudar a algún adulto mayor a hacerlo",
                                                                          value=10),
                                                             numericInput("p3.8",
                                                                          "Preparar remedios caseros o algún alimento especial a algún adulto mayor",
                                                                          value=10),
                                                             numericInput("p3.9",
                                                                          "Dar medicamentos o checar los síntomas de algún adulto mayor",
                                                                          value=10),
                                                             numericInput("p3.11",
                                                                          "Dar terapia especial o ayudar a realizar ejercicios a algún adulto mayor",
                                                                          value=10),
                                                             numericInput("p3.12",
                                                                          "Ayudar o apoyar en el trabajo de algún adulto mayor",
                                                                          value=10)))),
                                                             
                                                                ))),
      tabPanel("AMAI",
               sidebarLayout(
                 sidebarPanel(
                   h3("Hogar"),
                   flowLayout(selectInput("Esc_jefe",
                                          "¿Cuál es el máximo nivel de estudios del jefe de hogar?",
                                          c("No estudió",
                                            "Primaria incompleta",
                                            "Primaria completa",
                                            "Secundaria incompleta",
                                            "Secundaria completa",
                                            "Preparatoria incompleta",
                                            "Preparatoria completa",
                                            "Licenciatura incompleta",
                                            "Licenciatura completa",
                                            "Diplomado o maestría")),
                              numericInput(inputId="Numeroautos",
                                           label=" ¿Cuántos automóviles o camionetas tienen?",
                                           0,
                                           0,
                                           20),
                              radioButtons("Internet",
                                           "¿Su hogar cuenta con internet?",
                                           c("Si tengo","No tengo")),
                              sliderInput("Numerotrabajadores",
                                          "¿Cuántas personas mayores a 14 años trabajaron en el último mes?",
                                          0,
                                          20,
                                          5)),
                   h3("Vivienda"),
                   flowLayout(numericInput(inputId="Numerobaños",
                                           label="¿Cuántos baños completos hay en la vivienda?",
                                           0,
                                           0,
                                           20),
                              sliderInput("Numerocuartos",
                                          "¿cuántos cuartos se usan para dormir?",
                                          0,
                                          20,
                                          8))
               ),
               mainPanel(
                 h3("NSE"),
                 p("El", em("Índice de Niveles Socioeconómicos (NSE)"), ", creado por la", strong("Asociación Mexicana de agencias de Inteligencia de Mercado y Opinión (AMAI), "), "es la regla, basada en un modelo estadístico, que permite agrupar y clasificar a los hogares mexicanos en siete niveles, de acuerdo a su capacidad para satisfacer las necesidades de sus integrantes."),
                 textOutput("txtOutput"),
                 hr(),
                 img(src="imagen.png", align = "center", height = 420, width = 320),
                 img(src="imagen 2.png", align = "center", height = 420, width = 320))))
      
    )#tabsetPanel,
  )#fluidPage
)#ShinyUI